### ISSUE TITLE
Modules are not being loaded

### ISSUE THREAD

**Issue by speasley** [PerfectlyNormal/highcharts-rails#24]
Including:

```
//= require highcharts
//= require highcharts/highcharts-more
//= require highcharts/modules/exporting
//= require highcharts/modules/no-data-to-display
//= require highcharts/modules/solid-gauge
```

results in:

```
couldn't find file 'highcharts/modules/no-data-to-display'
couldn't find file 'highcharts/modules/solid-gauge'
```

Removing the offending modules allows it to load cleanly.

**Comment by PerfectlyNormal** [comment]
Hi.

Which version of the gem are you using? It works on my machine, but the asset pipeline has a reputation for being slightly difficult at times.

Additionally, have you restarted "everything" after including the gem? Sometimes that seems to trick it into working.
