### ISSUE TITLE
canvas-tools: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by NSinopoli** [PerfectlyNormal/highcharts-rails#27]
Thanks so much for your work on this gem!

Requiring the `canvas-tools` module causes an "Uncaught TypeError: Cannot read property 'prototype' of undefined" error. It's triggered by [this](https://github.com/PerfectlyNormal/highcharts-rails/blob/208a68788dd53f8a43c6cb5b118d05adae2b6c04/app/assets/javascripts/highcharts/modules/canvas-tools.js#L2940) line.

My `app/assets/javascripts/application.js`:

```
//= require highcharts
//= require highcharts/highcharts-more
//= require highcharts/modules/canvas-tools
//= require highcharts/modules/exporting
//= require highcharts/modules/no-data-to-display
```

Related:

http://stackoverflow.com/questions/16149147/highcharts-canvas-tools-cannot-read-property-prototype-of-undefined
https://github.com/highslide-software/highcharts.com/issues/2311

**Comment by PerfectlyNormal** [comment]
Thanks. Added a note to the readme, since that file is meant to be loaded by Highcharts when it's needed (https://github.com/highcharts/highcharts/issues/2311#issuecomment-25685317)
