### ISSUE TITLE
version 4.2.3

### ISSUE THREAD

**Issue by kbende** [PerfectlyNormal/highcharts-rails#32]
Hi,
I'm using the gem to manage my Highcharts installation.  I have an issue with v4.1.9.  There have been some updates (http://www.highcharts.com/documentation/changelog) and v4.2.3 resolves my issue.  Any chance we can get an update to the latest version?
Thank you,
Kevin

**Comment by PerfectlyNormal** [comment]
Hi

I've updated and released the last versions I've missed.
Thanks

**Comment by kbende** [comment]
Thanks for the quick response!
